# Generated by Django 6.0.3 on 2026-03-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourcategory_booking_status_tour_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='TourCategory',
        ),
    ]
